
name: (TEST) -Links

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  target:    'https://londonparkour.com'

jobs:

  linkcheck:

    runs-on: ubuntu-18.04
    name: BLC tests
    # RUN IF -links or -test in commit message
    if: "contains(github.event.head_commit.message, '-links') || contains(github.event.head_commit.message, '-test')"

    steps:

      - name: download blc
        run: |
          sudo npm install -g npm@latest
          sudo npm install -g broken-link-checker

      - name: run blc
        run: |
          set -x
          (blc --input https://staging.londonparkour.com -ro &>> /tmp/results.txt) || true

      - name: BLC Results
        uses: actions/upload-artifact@v2
        with:
          name: Results File  
          path: /tmp/results.txt