
name: (TEST) -validator

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  url: "https://staging.londonparkour.com/sitemap_index.xml"
  out: "/tmp/validator/"

jobs:

  validator:

    runs-on: ubuntu-latest
    name: Validator tests
    # RUN IF -validator or -test in commit message
    if: "contains(github.event.head_commit.message, '-validator') || contains(github.event.head_commit.message, '-test')"

    steps:


      - name: checkout repository
        uses: actions/checkout@v2


      # Run CURL On W3C Validator
      - name: Validate
        run: |
          mkdir ${{ env.out }}
          .github/workflows/setup/w3c_validate.sh ${{ env.url }} ${{ env.out }}


      - name: Validator Results
        uses: actions/upload-artifact@v2
        with:
          name: Validator Results  
          path: /tmp/validator/